config/routes.rb
Hyve4::Application.routes.draw do
  get "invites/new"

scope "(:locale)", :locale => /en|de/ do

  resources :users do
    member do
      get :following, :followers
      put :create_project
    end
  end

  resources :projects do
    member do
      get :category, :template, :groups
      put :update_category, :create_group, :update_group, :create_structure, :update_structure, :create_data, :update_email, :choose_template, :select_groups, :create_jsonstructure
    end
  end

  resources :structures do
    member do
      put :create_data, :update_dataval
    end
  end

  resources :invites,         only: [:create]
  resources :pjattribs
  resources :sessions,        only: [:new, :create, :destroy]
  resources :postings,        only: [:create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  root to: 'users#new'
  match "/blog"        => redirect("/blog/")
  match "/wp-admin"    => redirect("/wp-admin/")
  match "/crowdfunder" => redirect("/crowdfunder/")
  match '/imprint',   to: 'static_pages#imprint'
  match '/about',     to: 'static_pages#about'
  match '/plans',     to: 'static_pages#plans'
  match '/statistic', to: 'static_pages#statistic'
  match '/tour',      to: 'static_pages#tour'
  match '/signup',    to: 'users#new'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy'
  match '/email',     to: 'static_pages#email'
  match '/tracking',  to: 'static_pages#tracking'
  match '/privacy',   to: 'static_pages#privacy'
  match '/changelog', to: 'static_pages#changelog'
  match '/usecases',  to: 'static_pages#usecases'
  match '/developers', to: 'static_pages#developers'
  match '/investors', to: 'static_pages#investors'

  match '/usercount', to: 'users#count'

end

match ':not_found' => 'application#missing', :constraints => { :not_found => /.*/ }
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def statistic
    @datavals = Dataval.group("DATE_TRUNC('week', valdatime)").count.sort
    a=[]
    b=[]
    cnt=0
    @datavals.each do |r|
      cnt += r[1]
      a.push(cnt)
      b.push(Date.strptime(r[0]).strftime("%F"))
    end
    @graph = LazyHighCharts::HighChart.new('column') do |f|
      f.series(:name => "# Data Items", :data=> a)
      f.options[:xAxis][:categories] = b
      f.options[:chart][:defaultSeriesType] = "column"
    end
    @datavals = b.zip(a)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.de.html.erb
# encoding: UTF-8

<% provide(:title, 'Über Hyve.me') %>
<h1>Über Hyve.me</h1>
<h3>Einleitung</h3>
<p class="myfloat"><img align="right" src="/images/bigdata.jpg" width="200" alt="Big Data">Das Internet ermöglicht großen Firmen riesige Datenmengen über jeden Einzelnen zu sammeln, und so gezielt Werbung, Nachrichten und Suchergebnisse anzubieten. Die dafür zugrundeliegenden Techniken werden oft unter dem Begriff 'Big Data' zusammengefasst und waren bisher Unternehmen wir Google, Amazon oder Facebook vorbehalten. Es ist aber dein Recht auf diese Daten zuzugreifen und sie zu deinem Nutzen auszuwerten!</p>
<p>&nbsp;</p>

<h3>Mission</h3>
<p class="myfloat">Hyve.me stellt die allgemein akzeptierte Vorstellung in Frage, dass zur sinnvollen Auswertung von großen Datenmengen ein Team von Computerexperten und genügend Geld zur Verfügung stehen muss. (Algorithmen werden als zu komplex und Ergebnisse als zu vieldeutig interpretiert, als dass sie von nicht speziell geschultem Personen angewendet werden könnten.) Diese Vorurteile wollen wir aus der Welt schaffen, und daher haben wir zuerst den Prozess der Datenanalyse in überschaubare Schritte gegliedert und dann damit begonnen, die sich daraus ergebenden Fragen zu lösen.</p>
<p>Um bei dieseem schwierigen Unterfangen unser Ziel konsequent zu verolgen, haben wir folgende Richtlinien für uns festgehalten:</p>
<ol>
  <li><strong>Einfachheit:</strong> Big Data ist von Natur aus eine komplexe Angelegenheit. Um aber das Potenzial und die Möglichkeiten Einzelnen zugänglich zu machen, werden wir alles unternehmen, um dies so einfach wie möglich zu gestalten - aber nicht einfacher.</p>
  <li><strong>Privatsphäre:</strong> Wie leben in einer Zeit nach Wikileaks und Prism, und daher sollte niemand irgendjemanden außer sich selbst vertrauen, wenn es um Datensicherheit geht. Daher haben wir uns für einen innovativen Ansatz entschieden, und bieten alle Funktionen zum Sammeln, Speichern und Verarbeiten von Daten auch als lokale Version an: Damit sieht weder Hyve.me noch irgend jemand andere deine Daten und was du damit machst.</li>
  <li><strong>Offenheit:</strong> Um unseren Werten treu zu bleiben, veröffentlichen wir den Quelltext unserer Software unter einer Open Source Lizenz, machen Schnittstellen- und Datenstrukturdokumentation frei zugänglich und arbeiten eng zusammen mit der Community, um offene Fragen rasch zu klären.</li>
</ol>
<p>&nbsp;</p>

<h3>Funktionsumfang</h3>
<p>Neue Funktionen in der Version 0.4.130920:</p>
<ul>
  <li>Vorlagen für neue Projekte</li>
  <li>JSON Datenimport</li>
  <li>Erweiterte Datensammlung via Email</li>
</ul>
<p>Ursprüngliche Funktionen in Version 0.4.130715:</p>
<ul>
  <li>Benutzerverwaltung</li>
  <li>Neuigkeiten von Personen denen du folgst</li>
  <li>Speicherung von Projektdaten</li>
  <li>Datensammlung via Email</li>
  <li>Liste ähnlicher Projekte</li>
</ul>
<p>Frühere Versionen und deren Umfang: <%= link_to("Change Log", changelog_path) %> (nur in englischer Sprache verfügbar)<br>
Und schließlich, hier auch ein Ausblick auf zukünftige Versionen: <%= link_to("Pläne", plans_path) %></p>

app/views/static_pages/changelog.html.erb
<% provide(:title, 'Change Log') %>
<h1>Change Log</h1>
<h4>Version 0.4 - Summer '13</h4>
<ul>
  <li><strong>v0.4.130920:</strong> UX enhancements</li>
  <li><strong>v0.4.130715:</strong> first web app</li>
</ul>
<p>&nbsp;</p>
<h4>Version 0.3 - Spring '13</h4>
<ul>
  <li><strong>v0.3.130401:</strong> tour feature added</li>
  <li><strong>v0.3.130325:</strong> landing page and rudimentary workflow implemented with forum</li>
</ul>
<p>&nbsp;</p>
<h4>Version 0.2 - Early '13</h4>
<ul>
  <li><strong>v0.2.0213:</strong> new import, printing, test suite</li>
  <li><strong>v0.2.0130:</strong> initial release of an MS Access implementation</li>
</ul>
<p>&nbsp;</p>
<h4>Version 0.1 - Winter '12</h4>
<ul>
  <li><strong>v0.1:</strong> Google Docs implementation for data collection</li>
</ul>
<p>&nbsp;</p>
<h4>Version 0.0 - Autumn '12</h4>
<ul>
  <li><strong>Interviews:</strong> first user contact</li>
</ul>

app/views/static_pages/email.en.html.erb
<% provide(:title, 'Data Collection via Email') %>
<h1>Data Collection via Email</h1>
<h3>Background</h3>
<p class="myfloat">Hyve.me allows you to create for each project a data structure and periodically fill it with data.</p>
<img src="/images/datacollect.png" alt="Data Collection" width="500">
<p>&nbsp;</p>

<p class="myfloat">The problem with this type of data collection is that it is cumbersome and despite good intentions, people usually tend to abandon this task sooner or later. Quite some literature and tools exist about how to overcome those obstacles. Hyve.me in particular builds from the work of <a href="http://www.behaviormodel.org/">BJ Fogg's Behavior Model</a> - for an action (= collect data) to occur, three elements are necessary:</p>
<ul>
  <li><strong>Motivation:</strong> you want to collect data . Hyve.me assumes you do, otherwise you would not be at this website</li>
  <li><strong>Ability:</strong> it needs to be extremely simple to collect data</li>
  <li><strong>Triggers:</strong> you need to get reminders and include it in your daily workflow</li>
</ul>
<p class="myfloat">Hyve.me.s approach for simple data collection and including it in the daily workflow is to provide an email service to collect data.</p>
<p>&nbsp;</p>

<h3>Email Data Collection</h3>
<p class="myfloat">For each project you can enable 'Data collection via email':</p>
<img src="/images/emailsetting.png" alt="Toggle Email Data Collection" width="500">
<p>&nbsp;</p>

<p class="myfloat">With this function enabled you will receive an email each day asking to answer a specific aspect of your project. To avoid annoying users, the system will only send one mail per day and will only send the next question after a user have answered an email (i.e., if you don.t answer a Hyve-email for a week, you will also not get another email question for a week.)</p>
<p class="myfloat">The emails you receive from data@hyve.me are structured in the following way:</p>
<ol>
  <li><strong>Context:</strong> description of the question</li>
  <li><strong>Structure:</strong> how to format your response</li>
  <li><strong>Example:</strong> how would an example response look like (as a reference this is usually the response from last time you answered that question)</li>
  <li><strong>Insight (optional):</strong> when your data matches certain criteria Hyve.me informs you about identified patterns</li>
  <li><strong>Administration:</strong> general explanation about this mail and links to show/edit your data online</li>
  <li><strong>Overview:</strong> a list of all your data attributes you are collecting</li>
</ol>
<p class="myfloat">Also have a look at the <%= link_to "Plans page", plans_path %> to read about automatic data import coming soon.</p>

app/views/static_pages/imprint.de.html.erb
# encoding: UTF-8
<% provide(:title, 'Impressum') %>
<h1>Impressum</h1>
<p><img align="right" src="/images/cf.jpg" width="160" alt="Christoph Fabianek">Hyve.me - Big Data for Individuals</p>
<h3>Address</h3>
<p class="myfloat">Hyve.me<br>
Dr. Christoph Fabianek<br>
<a href="mailto:christoph.fabianek@hyve.me">christoph.fabianek@hyve.me</a><br>
Gerichtsstand, Bezirksgericht A-1010 Wien</p>
<p>&nbsp;</p>
<h3>Disclaimer</h3>
<p class="myfloat"><strong>Copyright</strong><br>
Hyve.me, nachfolgend &quot;Autor&quot; genannt, ist bestrebt, in allen Publikationen auf urheberrechtlich geschütztes Material zu verzichten, oder, falls nicht anders möglich, auf das Urheberrecht entsprechend hinzuweisen. Vom Autor selbst erstellte und veröffentliche Inhalte sind urheberrechtlich geschützt. Eine Vervielfältigung oder Verwendung solcher Grafiken, Tondokumente, Videosequenzen und Texte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdrückliche Zustimmung des Autors nicht gestattet.</p>
		
<p class="myfloat"><strong>Links &amp; Verweise</strong><br>
Der Autor ist nicht verantwortlich für direkte oder indirekte  Verweise auf fremde Internetseiten. Trotz aller Bemühungen ist es nicht immer möglich, Herkunft und Inhalt dieser Webseiten vollständig aufzuklären. Der Inhalt der Webseiten, auf die der Autor  verlinkt, ist grundsätzlich nicht Gegenstand des Angebotes des Autors, es sei denn, es wird gesondert darauf hingewiesen. Der Autor distanziert sich daher von diesen Inhalten und übernimmt keinerlei Haftung für durch diese Inhalte verursachte Schäden. Eine Haftungsverpflichtung würde  ausschließlich in dem Fall eintreten, in dem der Autor von den Inhalten Kenntnis hätte und es ihm technisch möglich und zumutbar wäre, die Nutzung im Falle rechtswidriger Inhalte zu verhindern. Die Verantwortung für diese Inhalte liegt allein beim Ersteller der jeweiligen  Webseite auf denen diese Inhalte liegen. Der Autor haftet nicht für Postings oder Nachrichten von Nutzern in Diskussionsforen, Gästebüchern oder Mailinglisten die auf seiner Seite zur Verfügung gestellt werden.</p>

<p class="myfloat"><strong>Inhalt</strong><br>
Der Autor übernimmt keinerlei Gewähr für die Aktualität, Korrektheit, Vollständigkeit oder Qualität der bereitgestellten Informationen. Für Schäden die durch die Nutzung der bereitgestellten Informationen, einschließlich jeglicher Art von Informationen, welche unvollständig oder falsch sind, verursacht werden, wird seitens des Autors keine Haftung übernommen.<br>
Alle Angebote sind freibleibend und unverbindlich. Teile der Seiten oder das gesamte Angebot einschließlich aller Angebote und Informationen können erweitert, geändert oder ganz oder teilweise vom Verfasser, ohne gesonderte Ankündigung, gelöscht werden.</p>

<p class="myfloat"><strong>Sonstiges</strong><br>
Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten, von dem aus auf diese Seite verwiesen wurde. Sofern Teile oder einzelne Formulierungen dieses Haftungsausschlusses unwirksam sind oder zukünftig werden, bleiben die übrigen Teile des Dokumentes in ihrem Inhalt und ihrer Gültigkeit davon unberührt.</p>
<p>&nbsp;</p>
		
<h3>Bilder</h3>
<p class="myfloat">Illustrative Grafiken wurden von <a href="http://123rf.com/">123RF - Royalty Free Stock Photos</a> erworben.</p>

app/views/static_pages/imprint.en.html.erb
<% provide(:title, 'Imprint') %>
<h1>Imprint</h1>
<p><img align="right" src="/images/cf.jpg" width="160" alt="Christoph Fabianek">Hyve.me - Big Data for Individuals</p>
<h3>Address</h3>
<p class="myfloat">Hyve.me<br>
Christoph Fabianek<br>
<a href="mailto:christoph.fabianek@hyve.me">christoph.fabianek@hyve.me</a><br>
Domestic place of general jurisdiction is A-1010 Vienna</p>
<p>&nbsp;</p>
<h3>Disclaimer</h3>
<p class="myfloat"><strong>Copyright</strong><br>
		Hyve.me, hereinafter known as &quot;author&quot; intended not to use any copyrighted material for the publication or, if not possible, to indicate the copyright of the respective object. The copyright for any material created by the author is reserved. Any duplication or use of objects such as diagrams, sounds or texts in other electronic or printed publications is not permitted without the author.s agreement.</p>
		
		<p class="myfloat"><strong>Links &amp; Referrals</strong><br>
		The author is not responsible for any contents linked or referred to from his pages . unless he has full knowledge of illegal contents and would be able to prevent the visitors of his site from viewing those pages. If any damage occurs by the use of information presented there, only the author of the respective pages might be liable, not the one who has linked to these pages. Furthermore the author is not liable for any postings or messages published by users of discussion boards, guestbooks or mailing-lists provided on his page.</p>

		<p class="myfloat"><strong>Content</strong><br>
		The author reserves the right not to be responsible for the topicality, correctness, completeness or quality of the information provided. Liability claims regarding damage caused by the use of any information provided, including any kind of information which is incomplete or incorrect, will therefore be rejected.<br>
		All offers are not-binding and without obligation. Parts of the pages or the complete publication including all offers and information might be extended, changed or partly or completely deleted by the author without separate announcement.</p>

		<p class="myfloat"><strong>Legal validity of this disclaimer</strong><br>
		This disclaimer is to be regarded as part of the internet publication which you were referred from. If sections or individual terms of this statement are not legal or correct, the content or validity of the other parts remain uninfluenced by this fact.</p>
		<p>&nbsp;</p>
		
		<h3>Images</h3>
		<p class="myfloat">Illustrative images are bought from <a href="http://123rf.com/">123RF - Royalty Free Stock Photos</a>.</p>

app/views/static_pages/imprint.html.erb
<% provide(:title, 'Imprint') %>
<h1>Imprint</h1>
<p><img align="right" src="/images/cf.jpg" width="160" alt="Christoph Fabianek">Hyve.me - Big Data for Individuals</p>
<h3>Address</h3>
<p>Hyve.me<br>
Christoph Fabianek<br>
<a href="mailto:christoph.fabianek@hyve.me">christoph.fabianek@hyve.me</a><br>
Domestic place of general jurisdiction is A-1010 Vienna</p>
<p>&nbsp;</p>
<h3>Disclaimer</h3>
<p><strong>Copyright</strong><br>
		Hyve.me, hereinafter known as &quot;author&quot; intended not to use any copyrighted material for the publication or, if not possible, to indicate the copyright of the respective object. The copyright for any material created by the author is reserved. Any duplication or use of objects such as diagrams, sounds or texts in other electronic or printed publications is not permitted without the author.s agreement.</p>
		
		<p><strong>Links &amp; Referrals</strong><br>
		The author is not responsible for any contents linked or referred to from his pages . unless he has full knowledge of illegal contents and would be able to prevent the visitors of his site from viewing those pages. If any damage occurs by the use of information presented there, only the author of the respective pages might be liable, not the one who has linked to these pages. Furthermore the author is not liable for any postings or messages published by users of discussion boards, guestbooks or mailing-lists provided on his page.</p>

		<p><strong>Content</strong><br>
		The author reserves the right not to be responsible for the topicality, correctness, completeness or quality of the information provided. Liability claims regarding damage caused by the use of any information provided, including any kind of information which is incomplete or incorrect, will therefore be rejected.<br>
		All offers are not-binding and without obligation. Parts of the pages or the complete publication including all offers and information might be extended, changed or partly or completely deleted by the author without separate announcement.</p>

		<p><strong>Legal validity of this disclaimer</strong><br>
		This disclaimer is to be regarded as part of the internet publication which you were referred from. If sections or individual terms of this statement are not legal or correct, the content or validity of the other parts remain uninfluenced by this fact.</p>
		<p>&nbsp;</p>
		
		<h3>Images</h3>
		<p>All images used on this site are bought from <a href="http://123rf.com/">123RF - Royalty Free Stock Photos</a>.</p>

app/views/static_pages/plans.de.html.erb
# encoding: UTF-8

<% provide(:title, 'Pläne') %>
<h1>Unsere Pläne</h1>
<p class="myfloat">Diese Seite gibt eine Ausblick auf die Entwicklung von Hybe.me. Natürlich wird sich dieser Plan mit der Zeit ändern, aber wir laden dich ein, uns jetzt schon über den Feedback Link am Ende der Seite deine Fragen und Anregungen mitzuteilen!</p>
<p>&nbsp;</p>
<h3>Herausforderungen</h3>
<p class="myfloat">Um Big Data einer breiten Masse zur Verfügung zu stellen, müssen vorher eine Reihe von Problemen gelöst werden. Bei Hyve.me werden wir an folgenden Themen arbeiten, von denen wir glauben, dass sie den Schlüssel zum Erfolg darstellen:</p>
<ul>
  <li><strong>Relevanz:</strong> Welche Daten sind relevant und geben Aufschluß zur gegebenen Problemstellung?<br>
Hyve.me zeigt automatisch eine Liste ähnlicher Projekte an und du kannst als Startpunkt jene Attribute verwenden die auch schon andere Projekte erfolgreich einsetzen.<br><br></li>

  <li><strong>Datenherkunft:</strong> Woher bekommt man diese Daten und wie importiert man sie?<br>
Das Ziel von Hyve.me ist einen automatischen Datenimport für bereits gespeicherte Daten anzubieten. Derzeit können Daten über diese Webseite oder über ein <%= link_to("Emailservice", email_path) %> erfasst werden.<br><br></li>

  <li><strong>Speicherung:</strong> Wo und wie können Daten sicher abgelegt werden?<br>
Derzeit verwendet Hyve.me zum Speichern aller Daten die <a href="http://aws.amazon.com/">Amazon Web Services</a>. Bald wird es möglich sein, dass du aber alternative Online-Anbieter auswählen kannst. Und schließlich soll es die Möglichkeit geben, dass jeder seine/ihre Daten am eigenen Computer ablegt.<br><br></li>

  <li><strong>Sicherheit:</strong> Wer kann meine Daten sehen?<br>
Das geplante Konzept von Hyve.me für Datensicherheit sieht ein fein-granulares Zugriffsrechte-Schema vor. Aktuell ist der Zugriff so konfiguriert, dass Attribute von Projekten allgemein sichtbar sind, aber die Daten selbst nur für den Besitzer verfügbar sind. D.h., andere sehen welche Daten du sammelst (z.B., Gasverbrauch pro Monat oder Kilometer gelaufen pro Tag), aber nicht die Werte selbst.<br><br></li>

  <li><strong>Vergleiche:</strong> Ist es möglich Daten mit anderen zu vergleichen, und trotzdem seine Privatsphäre zu schützen?<br>
Hyve.me schlägt eine Architektur und ein zugehöriges Protokoll zum sicheren Datenaustausch zwischen Gruppen von Benutzern vor. Dies ermöglicht statistische Analysen, ohne die eigenen Daten anderen preisgeben zu müssen.<br><br></li>

  <li><strong>Algorithmen:</strong> Wie kann ich meine Daten verarbeiten, um daraus neue Kenntnisse zu gewinnden?<br>
Hyve.me bietet ein Set an einfachen Analyse-Tools für deine Daten. Darüber hinaus wird es auch einen Markt (vergleichbar mit einem App-Store) geben, in dem Experten eigene Algorithem anbieten können. Jeder Benutzer kann sich so maßgeschneiderte Werkzeuge für seine Daten zusammenstellen.<br><br></li>

  <li><strong>Visualisierung:</strong> Wie können die Roh-Daten und auch Analyse-Ergebnisse interpretiert werden?<br>
Genauso wie bei Alogrithmen gibt es einfache grafische Darstellungen der Daten direkt bei Hyve.me. Und ebenfalls wird es die Möglichkeit für Visualisierungs-Experten im Markt geben ihre Erweiterungen anzubieten<br><br></li>

  <li><strong>Management:</strong> Wie kann ich den Wert von Daten bestimmen, falls ich Daten einkaufen, tauschen oder vekaufen möchte?<br>
Das eigentliche Ziel von Hyve.me ist es, Benutzern den Wert ihrer Daten konkret vor Augen zu führen. Derzeit werden oft dubiose Geschäfte mit privaten Daten durchgeführt und es ist nicht möglich, den dadurch entstanden Schaden zu beziffern. Durch die Etablierung eines Markts, auf dem Daten gehandelt werden können, wird es möglich sein durch Angbot und Nachfrage einen Wert für Daten zu bestimmen.</li>

app/views/static_pages/privacy.de.html.erb
# encoding: UTF-8

<% provide(:title, 'Datenzugriff') %>
<h1>Datenzugriff</h1>
<p class="myfloat">Diese Seite beschreibt auf welche Daten die Benutzer der Webseite zugreifen können.</p>
<h3>Besucher</h3>
<p class="myfloat">Benutzer die nicht bei Hyve.me angemeldet sind (= Besucher), können keine Daten von registrierten Benutzern einsehen, d.h., sie sehen nicht, wer auf dieser Seite ein Konto hat, sie sehen keine Projekte nd auch nicht die dazu gespeicherten Daten.</p>
<p>&nbsp;</p>
<h3>Angemeldete Benutzer</h3>
<p class="myfloat">Benutzer die bei Hyve.me ein Konto haben und eingeloggt sind, sehen folgende Informationen:</p>
<ul>
  <li>Liste aller registrierten Benutzer, aber nicht die Email-adresse dieser Benutzer (falls du mit anderen Benutzern in Kontakt treten möchtest, folge dieser Person und Poste eine Nachricht)</li>
  <li>Liste aller Projekte, samt der zugehörigen Liste an Attributen die dafür gesammelt werden, d.h., andere sehen welche Daten du erfasst, aber nicht die Daten selbst.</li>
</ul>
<p class="myfloat">Weitere Informationen über die geplanten Konfigurationsmöglichkeiten in Bezug auf Zugriffsrechte gibt es auf der Seite <%= link_to "Unsere Pläne", plans_path %>.</p>

app/views/static_pages/privacy.en.html.erb
<% provide(:title, 'Privacy') %>
<h1>Privacy</h1>
<p class="myfloat">This page describes who can see what on Hyve.me.</p>
<h3>Visitors</h3>
<p class="myfloat">People who did not sign-in on Hyve.me (= Visitors) can't see any of your data, i.e., don't see if you are signed up, don't see any of your projects, or an data associated to your projects.</p>
<p>&nbsp;</p>
<h3>Registered Users</h3>
<p class="myfloat">Users with an account on Hyve.me have the following access to data:</p>
<ul>
  <li>See the username of all other registered users; but don't see the email address of any other user (in case you want to get in contact with an other user you can follow this user and write a posting)</li>
  <li>See all projects from other users including what data is collected for that project - but not the data itself</li>
</ul>
<p class="myfloat">Have a look at the <%= link_to "Plans page", plans_path %> to see a description for a more fine grained access scheme that is planned in one of the next releases.</p>

app/views/static_pages/statistic.en.html.erb
<% provide(:title, 'Statistic') %>
<h1>Statistic</h1>
<p>This page is a sample for the data visualization in Hyve.me and shows the number of data items collected over time.</p>
<h3>Graph</h3>
<%= high_chart("my_bar_div", @graph) %>
    <h3>Data</h3>
      <table class="table table-striped table-bordered table-condensed">
        <thead><tr>
          <th>week</th>
          <th># Data Items</th>
        </tr></thead>
        <% @datavals.each do |d| %>
          <tr>
            <td><%= Date.strptime(d[0]).strftime("%F") %></td>
            <td><%= d[1] %></td>
          </tr>
        <% end unless @datavals.nil? %>
      </table>

app/views/static_pages/tour.de.html.erb
# encoding: UTF-8

<% provide(:title, 'Demo') %>
<h1>Demo</h1>
<h3>Der Start mit Hyve</h3>
<p>Nach dem Einloggen erwartet dich die Startseite mit Neuigkeiten von Personen denen du folgst (ähnlich wie Twitter).</p>
<img src="/images/userpage.png" alt="User Page" width="500">
<p>&nbsp;</p>
<h3>Deine Projekte</h3>
<p>Du kannst Projekt anlegen und beschreiben.</p>
<img src="/images/projectpage.png" alt="Project Page" width="500">
<p>&nbsp;</p>
<h3>Lerne von anderen</h3>
<p>Indem du dein Projekt kategorisierst, schlägt der Hyve.me ähnliche Projekte vor.</p>
<img src="/images/categorypage.png" alt="Category Page" width="500">
<p>&nbsp;</p>
<h3>Daten sammeln</h3>
<p>Entwickle eine Datenstruktur zur Dokumentation deiner Projekte und befülle sie mit Daten: Entweder durch Eingaben auf der Webseite oder durch Aktivierung der Datensammlung via Email.</p>
<img src="/images/datacollectpage.png" alt="Data Collection" width="500">
<p>&nbsp;</p>
<h3>Visualisierung</h3>
<p>Hyve.me erstellt Diagramme deiner Daten zum Erkennen von Trends.</p>
<img src="/images/graphpage.png" alt="Visualization Page" width="500">