config/routes.rb
Hyve4::Application.routes.draw do
  get "invites/new"

scope "(:locale)", :locale => /en|de/ do

  resources :users do
    member do
      get :following, :followers
      put :create_project
    end
  end

  resources :projects do
    member do
      get :category, :template, :groups
      put :update_category, :create_group, :update_group, :create_structure, :update_structure, :create_data, :update_email, :choose_template, :select_groups, :create_jsonstructure
    end
  end

  resources :structures do
    member do
      put :create_data, :update_dataval
    end
  end

  resources :invites,         only: [:create]
  resources :pjattribs
  resources :sessions,        only: [:new, :create, :destroy]
  resources :postings,        only: [:create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  root to: 'users#new'
  match "/blog"        => redirect("/blog/")
  match "/wp-admin"    => redirect("/wp-admin/")
  match "/crowdfunder" => redirect("/crowdfunder/")
  match '/imprint',   to: 'static_pages#imprint'
  match '/about',     to: 'static_pages#about'
  match '/plans',     to: 'static_pages#plans'
  match '/statistic', to: 'static_pages#statistic'
  match '/tour',      to: 'static_pages#tour'
  match '/signup',    to: 'users#new'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy'
  match '/email',     to: 'static_pages#email'
  match '/tracking',  to: 'static_pages#tracking'
  match '/privacy',   to: 'static_pages#privacy'
  match '/changelog', to: 'static_pages#changelog'
  match '/usecases',  to: 'static_pages#usecases'
  match '/developers', to: 'static_pages#developers'
  match '/investors', to: 'static_pages#investors'

  match '/usercount', to: 'users#count'

end

match ':not_found' => 'application#missing', :constraints => { :not_found => /.*/ }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  email                  :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  password_digest        :string(255)
#  remember_token         :string(255)
#  admin                  :boolean          default(FALSE)
#  password_reset_token   :string(255)
#  password_reset_sent_at :datetime
#  password_confirmation  :string(255)
#  invitecode             :string(255)
#  bio                    :text
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :invitecode, :password, :password_confirmation, :bio, :lastlogin, :logincnt
  has_secure_password
  has_many :postings, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :projects, dependent: :destroy

  attr_accessor :no_remember_token
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token, :unless => :no_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  def feed
    Posting.from_users_followed_by(self)
  end

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!(:validate => false)
    UserMailer.password_reset(self).deliver
  end

  def send_welcome
    UserMailer.welcome(self).deliver
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/users_controller.rb
include ActionView::Helpers::TextHelper

class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :show, :edit, :update, :destroy, :following, :followers]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  def show
    @user = User.find(params[:id])
    @postings = @user.postings.paginate(page: params[:page])
    @projects = @user.projects
  end

  def new
    if signed_in?
      @user = current_user
      @posting = current_user.postings.build
      @feed_items = current_user.feed.paginate(page: params[:page])
      @projects = @user.projects
      @project = current_user.projects.build
    else
      @user = User.new
      @invite = Invite.new
      @users = User.all
      @projects = Project.all
      @postings = Posting.all
      @datavals = Dataval.all
    end
  end

  def create
    if ENV['INVITE_CODE'].split(",").include?(params[:user][:invitecode])
      @user = User.new(params[:user])
      if @user.save
        sign_in @user
        @user.send_welcome
        flash[:success] = t('welcome.welcomeflash')
        flash[:info] = t('welcome.welcomehint')
        redirect_to root_path
      else
        flash[:error] = "Please fix the following " + pluralize(@user.errors.count, "error") + ": " + @user.errors.full_messages.join(", ")
        @invite = Invite.new
        @users = User.all
        @projects = Project.all
        @postings = Posting.all
        @datavals = Dataval.all
        render 'new'
      end
    else
      flash[:error] = t('welcome.invalidInvitecodemsg')
      redirect_to root_path
    end
  end

  def create_project
    @user = User.find(params[:id])
    @newproject=@user.projects.build(name: params['project']['name'], description: params['project']['description'])
    if @newproject.save
      flash[:success] = t('project.created')
      flash[:info] = t('project.createdHint')
      redirect_to project_path(@newproject.id)
    else
      flash[:error] = "Project not created because " + @newproject.errors.full_messages.join
      redirect_to user_path(params[:id])
    end
  end

  def create_invite
    if params[:commit] == t('welcome.submitbtn')
      flash[:success] = t('welcome.invitationFlash')
    else
      flash[:success] = t('welcome.publicBetaFlash')
    end
    redirect_to root_path
  end

  def index
    @users = User.paginate(page: params[:page], :order => 'LOWER(name) ASC')
  end

  def count
    render json: User.all.count
  end

  def edit
  end

  def update
    if params[:commit] == t('general.updatebtn')
      if @user.update_attributes(params[:user])
        flash[:success] = t('user.editSuccessmsg')
        sign_in @user
        redirect_to @user
      else
        render 'edit'
      end
    else
      User.find(params[:id]).destroy
      sign_out
      flash[:success] = t('user.editDeleteSuccessmsg')
      redirect_to root_path
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-success" %>
<% end %>

app/views/users/_follow_form.html.erb
<div id="follow_form">
<% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
<% else %>
  <%= render 'follow' %>
<% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, t('user.edittitle')) %> 
<h1 align="center"><%= t 'user.editheader' %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, t('general.name') %>
      <%= f.text_field :name %>

      <%= f.label :email, t('general.email') %>
      <%= f.text_field :email %>

      <%= f.label :password, t('general.password') %>
      <%= f.password_field :password %>

      <%= f.label :bio, t('user.biolbl') %>
      <%= f.text_area :bio, :rows => "3" %>

      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails"><%= t 'user.changeGravatar' %></a>

      <hr style="margin-top:40px; margin-bottom:10px;">

      <%= f.submit t('user.editDelete'), data: { confirm: t('general.Confirmmsg') }, class: "btn btn-danger" %>
      <%= f.submit t('general.updatebtn'), class: "btn btn-primary pull-right" %>&nbsp;
      <%= link_to t('general.closebtn'), user_path(params[:id]), class: "btn pull-right", style: "margin-right: 10px;"%>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, t('user.allUsersTitle')) %>
<h1><%= t('user.allUsersTitle') %> (<%= User.all.count %>)</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% if signed_in? %>
  <% provide(:title, current_user.name) %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <h3><%= t('user.projectheader') %></h3>
        <%= render 'shared/projectlist' %>
        <%= render 'shared/project_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3><%= t('user.postingfeedheader') %></h3>
      <section>
        <%= render 'shared/posting_form' %>
      </section>
      <section>
        <%= render 'shared/feed' %>
      </section>
    </div>
  </div>  
<% else %>  
  <% provide(:title, 'Home') %>
  <div id="heroimg" class="hero-unit">
    <div class="row-fluid">
	<div class="span12">
<div class="github-fork-ribbon-wrapper right fixed">
  <div class="github-fork-ribbon">
    <a href="http://www.crowdstatus.net">Crowd Status is online!<br><small>(click here to vist the first Hyve-App)</small></a>
  </div>
</div>

		<h1><%= t 'welcome.title' %></h1>
		<div class="row-fluid">
			<div class="span6">
				<h3 style="margin-top:30px;"><%= image_tag("write.png") %>&nbsp;&nbsp;<%= t 'welcome.writemsg' %></h3>
				<h3><%= image_tag("collect.png") %>&nbsp;&nbsp;<%= t 'welcome.collectmsg' %></h3>
				<h3><%= image_tag("compare.png") %>&nbsp;&nbsp;<%= t 'welcome.comparemsg' %></h3>
                                <p class="myfloat" style="margin-top: 18px;"><small><%= t 'welcome.betamsg' %></small></p>
				<p align="center"><a href="#inviteNew" role="button" data-toggle="modal" class="btn btn-large btn-success"><%= t 'welcome.invitationbtn' %></a></p>
			</div>
			<div class="span6">
				<p><br><%= t 'welcome.registermsg' %></p>
				<%= form_for @user, :html => {:class => "form-horizontal"} do |f| %>
					<fieldset>
						<div class="control-group">
						  <%= f.label :name, t('welcome.namelbl'), :class => "control-label", :style => "font-size: 18px;" %>
						  <div class="controls">
							  <%= f.text_field :name %>
						  </div>
						</div>
						<div class="control-group">
						  <%= f.label :email, t('welcome.emaillbl'), :class => "control-label", :style => "font-size: 18px;" %>
						  <div class="controls">
							<%= f.text_field :email %>
						  </div>
						</div>
						<div class="control-group">
						  <%= f.label :invitecode, t('welcome.invitecodelbl'), :class => "control-label", :style => "font-size: 18px;" %>
						  <div class="controls">
				  			  <%= f.text_field :invitecode, :id => "invitecode" %>
						  </div>
						</div>
                                                <div class="control-group">
                                                  <%= f.label :password, t('welcome.passwordlbl'), :class => "control-label", :style => "font-size: 18px;" %>
                                                  <div class="controls">
                                                          <%= f.password_field :password %>
                                                  </div>
                                                </div>
						<div class="control-group">
						  <div class="controls">
							<%= f.submit t('welcome.createbtn'), class: "btn btn-large btn-primary", id: "create_user" %>
						  </div>
						</div">
					</fieldset>
				<% end %>
			</div>
		</div>
	</div>
    </div>
  </div>

  <div class="row">
    <div class="span4">
	<h2 style="margin-bottom: 14px;"><%= t 'welcome.missiontitle' %></h2>
		<p><%= t 'welcome.missiontext' %></p>
		<p><%= link_to (t('welcome.missionbtn') + ' &raquo;').html_safe, about_path, :class => "btn" %></p>
    </div>
    <div class="span4">
		<h2 style="margin-bottom: 14px;"><%= t 'welcome.tourtitle' %></h2>
		<p><%= t 'welcome.tourtext' %></p>
		<p><%= link_to (t('welcome.tourbtn') + ' &raquo;').html_safe, tour_path, :class => "btn" %></p>
    </div>
    <div class="span4">
		<h2 style="margin-bottom: 14px;"><%= t 'welcome.statistictitle' %></h2>
		<p><%= t 'welcome.statistictext', :usercount => @users.present? ? @users.count : 0, :projectcount => @projects.present? ? @projects.count : 0, :postingcount => @postings.present? ? @postings.count : 0, :datacount => @datavals.present? ? @datavals.count : 0 %></p>
		<p><%= link_to (t('welcome.statisticbtn') + ' &raquo;').html_safe, statistic_path, :class => "btn" %></p>
    </div>
  </div>

<!-- Invitation Form -->
<%= form_for(@invite, :url => { :controller => 'invites', :action => 'create' }, :html => { class: "form-horizontal" } ) do |f| %>
  <div id="inviteNew" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="inviteNewLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3 id="inviteNewLabel"><%= t 'welcome.invitationtitle' %></h3>
      <%= t 'welcome.invitationtxt' %>
    </div>
    <div class="modal-body">
      <div class="control-group">
        <%= f.label :name, t('welcome.namelbl'), :class => "control-label" %>
        <div class="controls"><%= f.text_field :name %></div>
      </div>
      <div class="control-group">
        <%= f.label :email, t('welcome.emaillbl'), :class => "control-label" %>
        <div class="controls"><%= f.text_field :email %></div>
      </div>
      <div class="control-group">
        <%= f.label :bio, t('welcome.biolbl'), :class => "control-label" %>
        <div class="controls"><%= f.text_area :bio, :rows => "2" %></div>
      </div>
      <div class="control-group">
        <%= f.label :reason, t('welcome.reasonlbl'), :class => "control-label" %>
        <div class="controls"><%= f.text_area :reason, :rows => "2" %></div>
      </div>
      <%= t 'welcome.signuponly' %>
    </div>
    <div class="modal-footer">
      <%= f.submit(t('welcome.signupbtn'), :class => "btn btn-success pull-left") %>
      <button class="btn" data-dismiss="modal" aria-hidden="true"><%= t 'welcome.closebtn' %></button>
      <%= f.submit(t('welcome.submitbtn'), class: "btn btn-primary") %>
    </div>
  </div>
<% end %>

<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
        <% if current_user?(@user) %>
          <span class="subedit">
            <%= link_to('<i class="icon-pencil" style="position: absolute; margin-left: 5px; margin-top: 3px;"></i>'.html_safe, edit_user_path(current_user), rel: "tooltip", title: t('user.edittooltip'), class: "mylink") %>
          </span>
        <% end %>
      </h1>

<script>
$('h1').hover(function(){
$(this).children('.subedit').show();
},function(){
$(this).children('.subedit').hide();
});
</script>


      <%= render 'follow_form' if !current_user?(@user) %>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
    <section>
      <h4><%= t('user.projectheader') %> (<%= @user.projects.count %>)
        <% if current_user?(@user) %>
          <span class="subedit">
            <a href="#projectNew" role="button" data-toggle="modal" rel="tooltip" title=<%= t('user.editprojecttooltip') %> class="mylink"><i class="icon-plus" style="position: absolute; margin-left: 5px; margin-top: 3px;"></i></a>
          </span>
        <% end %>
      </h4>

<script>
$('h4').hover(function(){
$(this).children('.subedit').show();
},function(){
$(this).children('.subedit').hide();
});
</script>

<script>
$('.mylink').tooltip({ selector: "a" });
</script>

      <% if @user.projects.any? %>
        <ul>
          <%= render @projects %>
        </ul>        
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <% if @user.postings.any? %>
      <h3><%= t('user.postingheader') %> (<%= @user.postings.count %>)</h3>
      <ol class="postings">
        <%= render @postings %>
      </ol>
      <%= will_paginate @postings %>
    <% end %>
  </div>
</div>

<!-- New Project -->
<%= form_tag( { :action => 'create_project' }, { :method => 'put', :name => 'create_project', :class => "form-horizontal" } ) do %>
  <div id="projectNew" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="projectNewLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3 id="projectNewLabel"><%= t('project.newheader') %></h3>
    </div>
    <div class="modal-body">
      <div class="control-group">
        <%= label :project, :name, t('project.name'), :class => "control-label" %>
        <div class="controls"><%= text_field :project, :name %></div>
      </div>
      <div class="control-group">
        <%= label :project, :description, t('project.description'), :class => "control-label" %>
        <div class="controls"><%= text_area :project, :description, :rows => "2" %></div>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true"><%= t('general.closebtn') %></button>
      <%= submit_tag(t('general.createbtn'), class: "btn btn-primary") %>
    </div>
  </div>
<% end %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Postings:</b> <%= @user.postings.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>