config/routes.rb
Hyve4::Application.routes.draw do
  get "invites/new"

scope "(:locale)", :locale => /en|de/ do

  resources :users do
    member do
      get :following, :followers
      put :create_project
    end
  end

  resources :projects do
    member do
      get :category, :template, :groups
      put :update_category, :create_group, :update_group, :create_structure, :update_structure, :create_data, :update_email, :choose_template, :select_groups, :create_jsonstructure
    end
  end

  resources :structures do
    member do
      put :create_data, :update_dataval
    end
  end

  resources :invites,         only: [:create]
  resources :pjattribs
  resources :sessions,        only: [:new, :create, :destroy]
  resources :postings,        only: [:create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  root to: 'users#new'
  match "/blog"        => redirect("/blog/")
  match "/wp-admin"    => redirect("/wp-admin/")
  match "/crowdfunder" => redirect("/crowdfunder/")
  match '/imprint',   to: 'static_pages#imprint'
  match '/about',     to: 'static_pages#about'
  match '/plans',     to: 'static_pages#plans'
  match '/statistic', to: 'static_pages#statistic'
  match '/tour',      to: 'static_pages#tour'
  match '/signup',    to: 'users#new'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy'
  match '/email',     to: 'static_pages#email'
  match '/tracking',  to: 'static_pages#tracking'
  match '/privacy',   to: 'static_pages#privacy'
  match '/changelog', to: 'static_pages#changelog'
  match '/usecases',  to: 'static_pages#usecases'
  match '/developers', to: 'static_pages#developers'
  match '/investors', to: 'static_pages#investors'

  match '/usercount', to: 'users#count'

end

match ':not_found' => 'application#missing', :constraints => { :not_found => /.*/ }
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="postings">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= wrap(feed_item.content) %></span>
  <span class="timestamp">
    <%= t('user.postedlbl1') %> <%= time_ago_in_words(feed_item.created_at) %><%= t('user.postedlbl2') %>.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_posting_form.html.erb
<%= form_for(@posting, :url => { :controller => 'postings', :action => 'create' }) do |p| %>
  <%= render 'shared/error_messages', object: p.object %>
  <div class="field">
    <%= p.text_area :content, placeholder: t('user.composepostingHint'), :rows => "2" %>
  </div>
  <%= p.submit t('user.composepostingBtn'), id: "create_posting", class: "btn btn-large btn-primary pull-right" %>
<% end %>

app/views/shared/_project_form.html.erb
<%= form_for(@project, :url => { :controller => 'projects', :action => 'create' }, class: "form-horizontal") do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.text_field :name, placeholder: t('user.newprojectHint'), class: "input-xlarge" %>
  <%= f.submit t('user.newprojectBtn'), id: "create_project", class: "btn btn-large btn-primary pull-right", style: "margin-right: 30px" %>
<% end %>

app/views/shared/_projectlist.html.erb
<% if @user.projects.any? %>
  <ul>
    <%= render @projects[0...-1] %>
  </ul>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    <%= t('user.followinglbl') %>
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t('user.followerlbl') %>
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1 id="usertitle">
  <%= current_user.name %>
  <span class="subedit">
    <%= link_to('<i class="icon-pencil" style="position: absolute; margin-left: 5px; margin-top: 3px;"></i>'.html_safe, edit_user_path(current_user), :id => "user_hover_edit", :rel => "tooltip", :title => t('user.edittooltip'), :class => "mylink") %>
  </span>
</h1>

<script>
$('h1').hover(function(){
$(this).children('.subedit').show();
},function(){
$(this).children('.subedit').hide();
});
</script>

<script>
$('.mylink').tooltip({ selector: "a" });
</script>

<span>
  <%= link_to t('user.vierprofilelink'), current_user %>
</span>
<span>
  <%= current_user.postings.count %> <%= t('user.postinglbl') %>
</span>