config/routes.rb
Hyve4::Application.routes.draw do
  get "invites/new"

scope "(:locale)", :locale => /en|de/ do

  resources :users do
    member do
      get :following, :followers
      put :create_project
    end
  end

  resources :projects do
    member do
      get :category, :template, :groups
      put :update_category, :create_group, :update_group, :create_structure, :update_structure, :create_data, :update_email, :choose_template, :select_groups, :create_jsonstructure
    end
  end

  resources :structures do
    member do
      put :create_data, :update_dataval
    end
  end

  resources :invites,         only: [:create]
  resources :pjattribs
  resources :sessions,        only: [:new, :create, :destroy]
  resources :postings,        only: [:create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  root to: 'users#new'
  match "/blog"        => redirect("/blog/")
  match "/wp-admin"    => redirect("/wp-admin/")
  match "/crowdfunder" => redirect("/crowdfunder/")
  match '/imprint',   to: 'static_pages#imprint'
  match '/about',     to: 'static_pages#about'
  match '/plans',     to: 'static_pages#plans'
  match '/statistic', to: 'static_pages#statistic'
  match '/tour',      to: 'static_pages#tour'
  match '/signup',    to: 'users#new'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy'
  match '/email',     to: 'static_pages#email'
  match '/tracking',  to: 'static_pages#tracking'
  match '/privacy',   to: 'static_pages#privacy'
  match '/changelog', to: 'static_pages#changelog'
  match '/usecases',  to: 'static_pages#usecases'
  match '/developers', to: 'static_pages#developers'
  match '/investors', to: 'static_pages#investors'

  match '/usercount', to: 'users#count'

end

match ':not_found' => 'application#missing', :constraints => { :not_found => /.*/ }
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value|
     if !key.nil? && !value.nil?
       if key.to_s == "info" %>
         <div class="alert alert-block alert-info">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <h4><%= t('layout.hintlbl') %></h4>
           <%= value.html_safe %>
         </div>
    <% else %>
         <div class="alert alert-<%= key %>">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= value %>
         </div>
    <% end
     end
   end unless flash.nil? %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to_unless I18n.locale == :en, "English", params.merge(locale: "en") %> | <%= link_to_unless I18n.locale == :de, "Deutsch", params.merge(locale: "de") %> 
  </small>
  <nav class="pull-right" style="margin-bottom: -20px;">
    <ul>
      <li><%= link_to t('layout.imprint'), imprint_path %></li>
      <li><%= link_to "Blog", blog_path %></li>
      <li><%= link_to "Feedback", 'http://hyve.uservoice.com/' %>
    </ul>
  </nav>
  <div style="clear: both; text-align: right; margin-top: -10px;">
	<span style="float: left;"><small>&copy; Hyve.me 2013</small></span>
  	  <%= link_to image_tag("facebook.png", alt: "Facebook"), 'https://www.facebook.com/Hyve.me' %> | 
          <%= link_to image_tag("gplus.png", alt: "Goolge+"), 'https://plus.google.com/115523021927594181806', rel: "publisher" %> | 
          <%= link_to image_tag("twitter.png", alt: "Twitter"), 'https://twitter.com/HyveInfo' %>
  </div>
</footer>
<p>&nbsp;<p>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <nav>
            <ul class="nav">
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="/images/hyveico24.png" alt="Icon"><b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to t('layout.about'), about_path %></li>
                  <li><%= link_to t('layout.plans'), plans_path %></li>
                  <li><%= link_to t('layout.statistic'), statistic_path %></li>
                </ul>
              </li>
            </ul>
            <%= link_to "Hyve.me<sup><span style='text-transform:lowercase'>&alpha;</span></sup>".html_safe, root_path, id: "logo", style: "margin-left:-11px;" %>
            <ul class="nav pull-right">
			<% if signed_in? %>
              <li><%= link_to t('layout.home'), root_path %></li>
<!--              <li><%= link_to "Search", '#' %></li> -->
              <li><%= link_to t('layout.users'), users_path %></li>
              <li><%= link_to t('layout.projects'), projects_path %></li>
<!--              <li><%= link_to "Bazaar", '#' %></li> -->
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		<%= t 'layout.account' %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to t('layout.profile'), current_user %></li>
                  <li><%= link_to t('layout.settings'), edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to t('layout.signout'), signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
             <% else %>
              <li><%= link_to t('layout.signin'), signin_path %></li>
             <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %> 
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-36134421-2', 'hyve.us');
  ga('send', 'pageview');

</script>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div id="myflash"></div>
      <div id="flash_messages">
        <%= render :partial => 'layouts/flash', :locals => {:flash => flash} %>
      </div>
      <%= yield %>
    </div>
    <div class="container">
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>